jobs:
  create-update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: tests/nginx-deployment/deployment.yaml
          resource-name: deployment/nginx-deployment
          show-kubectl-command: true
orbs:
  kube-orb: circleci/kubernetes@x.y.z
version: 2.1
