jobs:
  create-update:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - install-kubectl
      - kube-orb/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: tests/nginx-deployment/deployment.yaml
          resource-name: deployment/nginx-deployment
          show-kubectl-command: true

version: 2.1
